name: Deploy Prod Auth Lambda

on:
  push:
    branches: [ main ]
    paths: 
        - "auth-lambda/"
        - "infra/auth-lambda.yml"
  workflow_dispatch: {}

jobs:
  deploy-auth-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build & Deploy (Auth Lambda)
        run: |
          # Build
          sam build --template-file infra/auth-lambda.yml

          # Deploy
          sam deploy \
            --stack-name free-app-auth-lambda-prod \
            --parameter-overrides \
              CognitoRegion=${{vars.AWS_REGION}} \
              CognitoUserPoolId=${{vars.COGNITO_USER_POOL_ID}} \
              StageName=Prod \
              "CloudFrontOrigin=\"'${{vars.CLOUDFRONT_URL}}'\"" \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM
