name: Deploy Cognito

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy-auth-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build & Deploy (Auth Lambda)
        run: |
          # Build
          sam build --template-file infra/auth-lambda.yml

          # Build the CORS origins string with inner single-quotes, as SAM expects
          ORIGIN_LIST="'http://localhost:5173,${{ vars.CLOUDFRONT_URL }}'"

          # Deploy
          sam deploy \
            --template-file infra/auth-lambda.yml \
            --stack-name free-app-auth-lambda \
            --parameter-overrides \
              CognitoRegion=us-west-2 \
              CognitoUserPoolId=us-west-2_xxxxxx \
              OriginList=$ORIGIN_LIST \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM
