name: Deploy Cognito

on:
  push:
    branches: [ main ]
    paths:
        - infra/auth-cognito.yml
  workflow_dispatch: {}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy CloudFormation stack (Cognito)
        run: |
          aws cloudformation deploy \
            --template-file infra/auth-cognito.yml \
            --stack-name ${{vars.APP_NAME}}-auth \
            --capabilities CAPABILITY_NAMED_IAM \
            --region ${{vars.AWS_REGION}} \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
                AppName=${{vars.APP_NAME}}    \
                CallbackUrl=${{vars.CALLBACK_URL}} \
                LogoutUrl=${{vars.LOGOUT_URL}} \
                DomainPrefix=${{vars.APP_NAME}}
